'use client';

import Link from 'next/link';
import { useState } from 'react';
import { Plus, UserRound } from 'lucide-react';
import { useDeliveryData } from '@/context/DeliveryDataContext';
import { DeliveryPartner, PartnerAvailability } from '@/types/delivery';

export default function DeliveryPartnersPage() {
  const { partners, addPartner, updatePartner, deletePartner } = useDeliveryData();
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState({ name: '', email: '', phone: '', password: 'demo123' });
  const submit = (event: React.FormEvent) => { event.preventDefault(); addPartner({ ...form, status: 'OFFLINE', isActive: true, maxConcurrentDeliveries: 3, averageDeliveryMinutes: 30, rating: 5 }); setForm({ name: '', email: '', phone: '', password: 'demo123' }); setShowForm(false); };
  return <div className="space-y-5"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold">Delivery Partners</h1><p className="text-sm text-gray-500">Manage availability and assignments</p></div><button onClick={() => setShowForm(!showForm)} className="flex items-center gap-2 rounded-xl bg-green-600 px-4 py-2.5 text-sm font-bold text-white"><Plus className="w-4 h-4" />Add partner</button></div>{showForm && <form onSubmit={submit} className="grid sm:grid-cols-4 gap-3 bg-white border border-gray-100 rounded-2xl p-4"><input required placeholder="Name" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} className="border rounded-xl p-2.5 text-sm" /><input required type="email" placeholder="Email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} className="border rounded-xl p-2.5 text-sm" /><input required placeholder="Phone" value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} className="border rounded-xl p-2.5 text-sm" /><button className="rounded-xl bg-slate-900 text-white font-bold text-sm">Create</button></form>}<div className="grid gap-3">{partners.map(partner => <PartnerRow key={partner.id} partner={partner} onToggle={() => updatePartner(partner.id, { isActive: !partner.isActive })} onStatus={status => updatePartner(partner.id, { status })} onDelete={() => deletePartner(partner.id)} />)}</div></div>;
}
function PartnerRow({ partner, onToggle, onStatus, onDelete }: { partner: DeliveryPartner; onToggle: () => void; onStatus: (status: PartnerAvailability) => void; onDelete: () => void }) { return <div className="bg-white rounded-2xl border border-gray-100 p-5 flex flex-wrap items-center gap-4"><div className="w-11 h-11 rounded-full bg-green-50 flex items-center justify-center"><UserRound className="w-5 h-5 text-green-600" /></div><div className="flex-1 min-w-[180px]"><Link href={`/admin/delivery-partners/${partner.id}`} className="font-bold hover:text-green-600">{partner.name}</Link><p className="text-xs text-gray-500">{partner.email} · {partner.phone}</p></div><div className="text-xs text-gray-500">{partner.activeDeliveries} active<br />{partner.completedDeliveries} completed</div><select value={partner.status} onChange={e => onStatus(e.target.value as PartnerAvailability)} className="border rounded-lg px-2 py-1.5 text-xs"><option>ONLINE</option><option>BUSY</option><option>OFFLINE</option></select><button onClick={onToggle} className={`text-xs font-bold px-3 py-2 rounded-lg ${partner.isActive ? 'bg-green-50 text-green-700' : 'bg-red-50 text-red-700'}`}>{partner.isActive ? 'Active' : 'Inactive'}</button><button onClick={onDelete} className="text-xs text-red-600">Delete</button></div>; }
